[global]
type=global
endpoint_identifier_order=ip,username,anonymous

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; ---- 1001 (browser softphone via Janus) ----
[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=opus
auth=1001
aors=1001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1001]
type=auth
auth_type=userpass
username=1001
password=pass1001

[1001]
type=aor
max_contacts=5
remove_existing=yes

; ---- 1002 (second endpoint / softphone) ----
[1002]
type=endpoint
context=internal
disallow=all
allow=ulaw
allow=alaw
allow=opus
auth=1002
aors=1002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1002]
type=auth
auth_type=userpass
username=1002
password=pass1002

[1002]
type=aor
max_contacts=5
remove_existing=yes
